/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReclamationsRouteImport } from './routes/reclamations'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as IndexRouteImport } from './routes/index'

const ReclamationsRoute = ReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reclamations': typeof ReclamationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reclamations': typeof ReclamationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/reclamations': typeof ReclamationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commandes'
    | '/community'
    | '/login'
    | '/parametres'
    | '/reclamations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commandes'
    | '/community'
    | '/login'
    | '/parametres'
    | '/reclamations'
  id:
    | '__root__'
    | '/'
    | '/commandes'
    | '/community'
    | '/login'
    | '/parametres'
    | '/reclamations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandesRoute: typeof CommandesRoute
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  ReclamationsRoute: typeof ReclamationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reclamations': {
      id: '/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof ReclamationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandesRoute: CommandesRoute,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  ReclamationsRoute: ReclamationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
